ARG ALPINE_VERSION=latest
FROM alpine:${ALPINE_VERSION} as apkextractor

ARG PACKAGES=musl
ARG ADDFILES

COPY apkextractor.sh /
RUN /apkextractor.sh ${PACKAGES}

FROM scratch
COPY --from=apkextractor /target /
