#!/bin/sh

echo "------ HOOK START - $0 -------"

#m4 -I ../ Dockerfile.m4 > Dockerfile

cp ../apkextractor.sh ./

(
 cat ../Dockerfile-apkbase.m4
 echo '
ENTRYPOINT [ "/usr/bin/socat" ]
CMD [ "--help" ]
'
) > Dockerfile

cat Dockerfile

#echo "socat so:libncursesw.so.6" > PACKAGES

echo "------ HOOK END - $0 -------"
