#!/bin/sh

echo "------ HOOK START - $0 -------"

(
 cat ../Dockerfile
 echo ENTRYPOINT [ "/usr/bin/socat" ]
 echo CMD [ "--help" ]
) > Dockerfile

echo 'socat' > PACKAGES

echo "------ HOOK END - $0 -------"
