#!/bin/sh

echo "------ HOOK START - $* -------"

PACKAGES="$(sed -ne '1s/^#//p' "$DOCKER_TAG.part")" #first line : PACKAGES
ADDFILES="$(sed -ne '2s/^#//p' "$DOCKER_TAG.part")" #second line: ADDFILES

docker build\
 --build-arg PACKAGES="$PACKAGES"\
 --build-arg ADDFILES="$ADDFILES"\
 -t $IMAGE_NAME .

echo "------ HOOK END - $* -------"
