#!/bin/sh

echo "------ HOOK START - $* -------"

PACKAGES="$(sed -ne '1s/^#//p' "$DOCKER_TAG.part")"
AFTERRUN="echo Afterrun; $(sed -ne '2s/^#//p' "$DOCKER_TAG.part")"

docker build\
 --build-arg PACKAGES="$PACKAGES"\
 --build-arg AFTERRUN="$AFTERRUN"\
 -t $IMAGE_NAME .

echo "------ HOOK END - $* -------"
