#!/bin/sh

echo "------ HOOK START - $* -------"

PACKAGES="$(sed -ne '1s/^#//p' "$DOCKER_TAG.part")"

docker build --build-arg PACKAGES="$PACKAGES" -t $IMAGE_NAME .

echo "------ HOOK END - $* -------"
