---
name: 'build and deploy images'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '15 4 * * sun'

jobs:
  alpine-based:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        alpine-version: [ edge, latest ]
        name: [ socat, tor, svn, jq, xmlstarlet, curl ]
        command: '[ "--help" ]'
        include:
          # Example
          - name: openjdk8-jre
            packages: openjdk8-jre ca-certificates-bundle
            files: 'etc/ssl/cert.pem etc/ssl/certs/ca-certificates.crt'
            entrypoint: '[ "java" ]'
            command: '[ "-version" ]'
            dockerfile-bottom: |
             ENV PATH=/usr/lib/jvm/java-1.8-openjdk/bin

          - name: socat
            command: '[ "-h" ]'

          - name: svn
            packages: subversion
            files: 'etc/ssl/cert.pem etc/ssl/certs/ca-certificates.crt'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        id: prep
        run: |
         DOCKER_IMAGE=${{ secrets.DOCKERHUB_USER }}/tiny

         # Calculate Image TAG
         case '${{ matrix.alpine-version }}' in
          'edge') TAG="${DOCKER_IMAGE}:${{matrix.name}}-edge" ;;
          *     ) TAG="${DOCKER_IMAGE}:${{matrix.name}}"      ;;
         esac

         # Calculate packages list
         PACKAGES='${{matrix.name}}'
         [ -z '${{matrix.packages}}' ] || PACKAGES='${{matrix.packages}}'

         # Do the tinyimages magic here
         {
          [ -z '${{ matrix.entrypoint }}' ] && echo ENTRYPOINT [ "/usr/bin/${{matrix.name}}" ] || echo ENTRYPOINT '${{ matrix.entrypoint }}'
          [ -z '${{ matrix.command }}' ] || echo CMD '${{ matrix.command }}'
          echo '${{ matrix.dockerfile-bottom }}';
         } >> ./Dockerfile-alpine

         # Set output parameters.
         echo ::set-output name=tag::${TAG}
         echo ::set-output name=packages::${PACKAGES}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-alpine
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.prep.outputs.tag }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine-version }}
            PACKAGES=${{ steps.prep.outputs..packages }}
            ADDFILES=${{ matrix.files }}

      - name: Test default arch
        env:
          COMPOSE_FILE: ./tests/compose-sut.yaml
          IMAGE_NAME: ${{ steps.prep.outputs.tag }}
        run: |
         TEST_LOG="$(mktemp)"
         docker-compose --verbose --no-ansi up sut | tee "${TEST_LOG}"
         tail --lines=1 "${TEST_LOG}" | grep '^tests_sut_1 exited with code 0$'
         rm "${TEST_LOG}"
         docker-compose down

         docker run -i "${IMAGE_NAME}"
         podman run -i "${IMAGE_NAME}"
