---
name: 'build and deploy images'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '15 4 * * sun'

jobs:
  alpine-based:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        alpine-version: [ latest, edge ]
        name: [ socat, tor, svn, jq, xmlstarlet, curl, perl, perl-utils ]
        include:
#          # Example
#          - name: java # Please add this name to the matrix names list above!
#            packages: openjdk8-jre ca-certificates-bundle # Default: ${{matrix.name}}
#            files: 'etc/ssl/cert.pem etc/ssl/certs/ca-certificates.crt' # Add certain files, not packages
#            entrypoint: '[ "java" ]'                      # Default: '[ "/usr/bin/${{matrix.name}}" ]'
#            command: '[ "-version" ]'                     # Default: '[ "--help" ]'
#            dockerfile-bottom: |
#             ENV PATH=/usr/lib/jvm/java-1.8-openjdk/bin

          - name: socat
            command: '[ "-h" ]'

          - name: svn
            packages: subversion
            files: 'etc/ssl/cert.pem etc/ssl/certs/ca-certificates.crt'

          - name: curl
            files: 'etc/ssl/cert.pem etc/ssl/certs/ca-certificates.crt'

          - name: perl-utils
            entrypoint: '[ "/usr/bin/perl" ]'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        id: prep
        run: |
         set -x
         DOCKER_IMAGE=${{ secrets.DOCKERHUB_USER }}/tiny

         # Calculate Image TAG
         case '${{ matrix.alpine-version }}' in
          'edge') TAG="${DOCKER_IMAGE}:${{matrix.name}}-edge" ;;
          *     ) TAG="${DOCKER_IMAGE}:${{matrix.name}}"      ;;
         esac

         # Calculate packages list
         PACKAGES='${{matrix.name}}'
         [ -z '${{matrix.packages}}' ] || PACKAGES='${{matrix.packages}}'

         # Do the tinyimage magic here
         {
          # Set default entrypoint?
          if [ -z '${{ matrix.entrypoint }}' ]; then
           echo ENTRYPOINT "[ \"/usr/bin/${{matrix.name}}\" ]"
           else echo ENTRYPOINT '${{ matrix.entrypoint }}'
          fi

          # Set default comand?
          if [ -z '${{ matrix.command }}' ]; then
           echo CMD '[ "--help" ]'
           else echo CMD '${{ matrix.command }}'
          fi

          # Print custom rest of the Dockerfile
          echo '${{ matrix.dockerfile-bottom }}';
         } >> ./Dockerfile-alpine

         # Set output parameters.
         echo ::set-output name=tag::${TAG}
         echo ::set-output name=packages::${PACKAGES}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Simple build and run test
        env:
          COMPOSE_FILE: ./tests/compose-sut.yaml:./tests/compose-build-sut.yaml
          IMAGE_NAME: test:${{matrix.name}}
          ALPINE_VERSION: ${{ matrix.alpine-version }}
          PACKAGES: ${{ steps.prep.outputs.packages }}
          ADDFILES: ${{ matrix.files }}
        run: |
         set -x
         TEST_LOG="$(mktemp)"
         docker-compose --no-ansi up --build sut | tee "${TEST_LOG}"
         docker-compose down
         test "$(tail --lines=1 ${TEST_LOG})" '==' 'tests_sut_1 exited with code 0'
         rm "${TEST_LOG}"

      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-alpine
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.prep.outputs.tag }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine-version }}
            PACKAGES=${{ steps.prep.outputs.packages }}
            ADDFILES=${{ matrix.files }}

      - name: After push default arch test
        env:
          COMPOSE_FILE: ./tests/compose-sut.yaml
          IMAGE_NAME: ${{ steps.prep.outputs.tag }}
        run: |
         set -x
         TEST_LOG="$(mktemp)"
         docker-compose --no-ansi up sut | tee "${TEST_LOG}"
         docker-compose down
         test "$(tail --lines=1 ${TEST_LOG})" '==' 'tests_sut_1 exited with code 0'
         rm "${TEST_LOG}"

         docker run -i "${IMAGE_NAME}"
         podman run -i "${IMAGE_NAME}"
